# Generated by Django 5.0 on 2024-01-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles_table',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
