# Generated by Django 5.0 on 2024-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0003_vehicles_table_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles_table',
            name='rent_start',
            field=models.DateTimeField(null=True),
        ),
    ]
