# Generated by Django 5.0 on 2024-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_vehicles_table_rent_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles_table',
            name='rent_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
