# Generated by Django 5.0 on 2024-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0006_vehicles_table_currently_rented_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles_table',
            name='rent_start',
            field=models.DateTimeField(),
        ),
    ]
