# Generated by Django 5.0 on 2024-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_bio_user_earning_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spending',
            field=models.IntegerField(null=True),
        ),
    ]
