# Generated by Django 5.0 on 2024-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='earning',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spending',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
