# Generated by Django 5.0 on 2024-01-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
